# Import libraries

In [7]:
from pathlib import Path
import sqlite3
import pandas as pd
Path('my_data.db').touch()

# Build a star data model in Sqlite

In [8]:
conn = sqlite3.connect('Data2.db')
c = conn.cursor()

## loans table

In [9]:
c.execute('''CREATE TABLE loans (Project_ID text, End_of_Period text, Loan_Number text, Region text, Country_Code text,
       Borrower text, Guarantor text, Interest_Rate FLOAT, Currency_of_Commitment FLOAT)''')
# load the data into a Pandas DataFrame
loans = pd.read_csv('loans.csv')
# write the data to a sqlite table
loans.to_sql('loans', conn, if_exists='append', index = False)

## project table

In [10]:
c.execute('''CREATE TABLE project (Project_ID text, Project_Name text, Original_Principal_Amount FLOAT, Cancelled_Amount FLOAT,Undisbursed_Amount FLOAT, 
Disbursed_Amount FLOAT, Repaid_to_IBRD FLOAT, Due_to_IBRD FLOAT, Exchange_Adjustment FLOAT, Borrower_Obligation FLOAT,Sold_3rd_Party FLOAT,Repaid_3rd_Party FLOAT,Due_3rd_Party FLOAT,Loans_Held FLOAT
)''')

In [11]:
# load the data into a Pandas DataFrame
project = pd.read_csv('project.csv')
# write the data to a sqlite table
project.to_sql('project', conn, if_exists='append', index = False)

In [12]:
pd.read_sql('''SELECT * FROM loans u LEFT JOIN project o ON u.Project_ID = o.Project_ID''', conn)

,Project_ID,End_of_Period,Loan_Number,Region,Country_Code,Borrower,Guarantor,Interest_Rate,Currency_of_Commitment,Project_ID,...,Undisbursed_Amount,Disbursed_Amount,Repaid_to_IBRD,Due_to_IBRD,Exchange_Adjustment,Borrower_Obligation,Sold_3rd_Party,Repaid_3rd_Party,Due_3rd_Party,Loans_Held
0,P037383,2020-11-30T00:00:00.000,IBRD00010,EUROPE AND CENTRAL ASIA,FR,CREDIT NATIONAL,France,4.25,None,P037383,...,0.0,2.500000e+08,3.800000e+04,0.000000e+00,0.000000e+00,0.0,2.499620e+08,2.499620e+08,0.0,0.000000e+00
1,P037452,2020-11-30T00:00:00.000,IBRD00020,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,P037452,...,0.0,3.955788e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.0,3.955788e+06,3.955788e+06,0.0,0.000000e+00
2,P037452,2020-11-30T00:00:00.000,IBRD00020,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,P037452,...,0.0,1.910442e+08,1.033722e+08,0.000000e+00,0.000000e+00,0.0,8.767200e+07,8.767200e+07,0.0,0.000000e+00
3,P037452,2020-11-30T00:00:00.000,IBRD00021,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,P037452,...,0.0,3.955788e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.0,3.955788e+06,3.955788e+06,0.0,0.000000e+00
4,P037452,2020-11-30T00:00:00.000,IBRD00021,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,P037452,...,0.0,1.910442e+08,1.033722e+08,0.000000e+00,0.000000e+00,0.0,8.767200e+07,8.767200e+07,0.0,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,P004894,2020-11-30T00:00:00.000,IBRDS0160,MIDDLE EAST AND NORTH AFRICA,DZ,MINISTERE DES FINANCES,Algeria,0.00,None,P004894,...,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00
14996,P004895,2020-11-30T00:00:00.000,IBRDS0170,MIDDLE EAST AND NORTH AFRICA,DZ,MINISTERE DES FINANCES,Algeria,7.95,None,P004895,...,0.0,3.611691e+06,3.611691e+06,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00
14997,P005392,2020-11-30T00:00:00.000,IBRDS0180,MIDDLE EAST AND NORTH AFRICA,MA,ONAREP,Morocco,8.25,None,P005392,...,0.0,4.989608e+07,4.989608e+07,7.450000e-09,-7.450000e-09,0.0,0.000000e+00,0.000000e+00,0.0,7.450000e-09
14998,P007969,2020-11-30T00:00:00.000,IBRDS0190,LATIN AMERICA AND CARIBBEAN,PE,EMPRESA SIDERURGICA DEL PERU,Peru,8.25,None,P007969,...,0.0,1.356857e+06,1.356857e+06,2.330000e-10,-2.330000e-10,0.0,0.000000e+00,0.000000e+00,0.0,2.330000e-10
14999,P005939,2020-11-30T00:00:00.000,IBRDS0200,LATIN AMERICA AND CARIBBEAN,AR,Ministry of Treasury,Argentina,9.25,None,P005939,...,0.0,1.000000e+07,1.000000e+07,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00

# Prepare Data

In [13]:
def wrangle(db_path):
    # Connect to database
    conn = sqlite3.connect(db_path)

    # Construct query
    query = """
        SELECT * FROM loans u LEFT JOIN project o ON u.Project_ID = o.Project_ID
    """

    # Read query results into DataFrame
    df = pd.read_sql(query, conn, index_col="Project_ID")

    return df

In [14]:
df = wrangle("Data2.db")
df.head()

,End_of_Period,Loan_Number,Region,Country_Code,Borrower,Guarantor,Interest_Rate,Currency_of_Commitment,Project_Name,Original_Principal_Amount,...,Undisbursed_Amount,Disbursed_Amount,Repaid_to_IBRD,Due_to_IBRD,Exchange_Adjustment,Borrower_Obligation,Sold_3rd_Party,Repaid_3rd_Party,Due_3rd_Party,Loans_Held
Project_ID,,,,,,,,,,,,,,,,,,,,,
"(P037383, P037383)",2020-11-30T00:00:00.000,IBRD00010,EUROPE AND CENTRAL ASIA,FR,CREDIT NATIONAL,France,4.25,None,RECONSTRUCTION,2.500000e+08,...,0.0,2.500000e+08,38000.0,0.0,0.0,0.0,2.499620e+08,2.499620e+08,0.0,0.0
"(P037452, P037452)",2020-11-30T00:00:00.000,IBRD00020,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,RECONSTRUCTION,3.955788e+06,...,0.0,3.955788e+06,0.0,0.0,0.0,0.0,3.955788e+06,3.955788e+06,0.0,0.0
"(P037452, P037452)",2020-11-30T00:00:00.000,IBRD00020,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,RECONSTRUCTION,1.910442e+08,...,0.0,1.910442e+08,103372211.8,0.0,0.0,0.0,8.767200e+07,8.767200e+07,0.0,0.0
"(P037452, P037452)",2020-11-30T00:00:00.000,IBRD00021,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,RECONSTRUCTION,3.955788e+06,...,0.0,3.955788e+06,0.0,0.0,0.0,0.0,3.955788e+06,3.955788e+06,0.0,0.0
"(P037452, P037452)",2020-11-30T00:00:00.000,IBRD00021,EUROPE AND CENTRAL ASIA,NL,None,None,4.25,None,RECONSTRUCTION,1.910442e+08,...,0.0,1.910442e+08,103372211.8,0.0,0.0,0.0,8.767200e+07,8.767200e+07,0.0,0.0

# Dashboard

In [15]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd


external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)


df['End_of_Period'] = pd.to_datetime(df['End_of_Period'])

df['Year'] = pd.DatetimeIndex(df['End_of_Period']).year

graph = dcc.Graph(id='interactive-chart')

date_slider = dcc.RangeSlider(
    id='year-slider',
    min=df['End_of_Period'].min().year,
    max=df['End_of_Period'].max().year,
    value= [df['End_of_Period'].min().year, df['End_of_Period'].max().year],
    marks = {str(year): str(year) for year in df['Year'].unique()},
    step=None)

app.layout = html.Div([graph, date_slider])

### Within update_figure, create a filtered dataset using the range set by the RangeSlider
### The fig now uses the filtered dataset
### The fig_title is also updated
### Sliding the RangeSlider causes the chart to be updated with the filtered dataset

@app.callback(
    dash.dependencies.Output('interactive-chart', 'figure'),
    [dash.dependencies.Input('year-slider', 'value')])
def update_figure(value):
    filtered_data = df[(df['Year'] >= value[0]) \
                                & (df['Year'] <= value[1])]
    fig = px.line(filtered_data,
                  x="Date", y="Adj Close")
    fig_title = 'S&P 500 from ' + str(value[0]) + ' to ' + str(value[1])
    fig.update_layout(title_text = fig_title)
    
    return fig



if __name__ == '__main__':
    app.run_server(debug=True)

Dash is running on http://127.0.0.1:8050/

D:\ProgramFiles\anaconda3\envs\gis\lib\site-packages\ipykernel_launcher.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

D:\ProgramFiles\anaconda3\envs\gis\lib\site-packages\ipykernel_launcher.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  This is separate from the ipykernel package so we can avoid doing imports until
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

D:\ProgramFiles\anaconda3\envs\gis\lib\site-packages\IPython\core\interactiveshell.py:3465: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

# Send Email

In [16]:
df = df.describe().reset_index()

In [17]:
df

,index,Interest_Rate,Original_Principal_Amount,Cancelled_Amount,Undisbursed_Amount,Disbursed_Amount,Repaid_to_IBRD,Due_to_IBRD,Exchange_Adjustment,Borrower_Obligation,Sold_3rd_Party,Repaid_3rd_Party,Due_3rd_Party,Loans_Held,Year
0,count,14744.000000,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,1.467400e+04,15000.0
1,mean,4.500755,7.307605e+07,9.777532e+06,5.575546e+06,5.800099e+07,4.000392e+07,1.784161e+07,4.399283e+04,1.788560e+07,2.692368e+05,2.692368e+05,-6.187815e-13,2.341715e+07,2020.0
2,std,3.321934,1.392894e+08,4.149982e+07,3.594605e+07,1.249891e+08,8.584829e+07,8.855644e+07,1.132056e+07,8.665688e+07,3.017095e+06,3.017095e+06,6.228724e-11,9.847711e+07,0.0
3,min,0.000000,0.000000e+00,0.000000e+00,-1.000000e-02,-1.490000e-08,0.000000e+00,-1.005074e+08,-6.883102e+08,-1.700000e-01,0.000000e+00,0.000000e+00,-3.730000e-09,-1.005074e+08,2020.0
4,25%,0.620000,8.500000e+06,0.000000e+00,0.000000e+00,4.744032e+06,2.284121e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2020.0
5,50%,5.500000,2.762571e+07,0.000000e+00,0.000000e+00,1.929686e+07,1.313330e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2020.0
6,75%,7.250000,8.056530e+07,3.538462e+06,0.000000e+00,5.851799e+07,4.198284e+07,4.660000e-10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.310000e-10,2020.0
7,max,16.790000,3.750000e+09,1.995000e+09,1.000000e+09,3.110973e+09,3.000000e+09,2.664932e+09,2.942756e+08,1.976622e+09,2.499620e+08,2.499620e+08,3.730000e-09,2.977131e+09,2020.0

In [19]:
df.shape

(8, 15)

In [18]:
df.to_html('df.html',border=0)

In [ ]:
for i in range(df.shape[0]):
    for j in range(df.shape[1]): 
        print (i,j)

In [ ]:
#Creating the HTML Table

def create_html_table(x):
    
    row_data = ''

    for i in range(x.shape[0]):

        for j in range(x.shape[1]):        
            if ((i % 2) != 0) & (j == 0): #not an even row and the start of a new row
                row_data += '\n<tr style="background-color:#f2f2f2"> \n <td class = "text_column">'+str(x.iloc[i,j])+'</td>'

            elif j == 0: #The first column
                row_data += '\n<tr> \n <td class = "text_column">'+str(x.iloc[i,j])+'</td>'
            
            elif j == 1: #second column
                row_data += '\n <td class = "number_column">'+str(x.iloc[i,j])+'</td>'
            
            elif j == 2: #third column and our last column in my example
                row_data += ' <td class = "number_column">'+str(x.iloc[i,j])+'</td> \n </tr>'

            else:
                row_data += '\n <td class = "number_column">'+str(x.iloc[i,j])+'</td>'
                
    return row_data

In [ ]:
df.shape

In [ ]:
html_table = create_html_table(df)

In [ ]:
html_file = '''

<!DOCTYPE html>
<html>
<head>
<style>
table {
  border-collapse: collapse;
  width: 30%;
}

th, td {
  padding: 6px;
  font-family: Helvetica, Arial, Helvetica;
  font-size: 12px;
}


.header {
  color: white;
  background-color: black;
  border-bottom:1pt solid black;
}

.text_column {
  text-align: left;
}

.number_column {
  text-align: right;
}

.even_row {
background-color: #f2f2f2;
}

</style>
</head>

<body>
  <h1>HTML Table From a Pandas DataFrame!</h1>

<div style="overflow-x:auto;">

<table>
  <thead>
    <tr class = "header">
      <th class = "text_column">'''+df.columns[0]+'''</th>
      <th class = "number_column">'''+df.columns[1]+'''</th>
      <th class = "number_column">'''+df.columns[2]+'''</th>
    </tr>
  </thead>
  <tbody>
''' +html_table+ '''
  </tbody>
  </table>
</div>

</div>
</body>
</html>

'''

In [ ]:
os.remove('df_from_loop.html')
with open('df_from_loop.html', 'a') as f:
    f.write(html_file)

In [ ]:
import os
import smtplib
import imghdr
from email.message import EmailMessage

email = os.environ.get('email_address')
password = os.environ.get('gmail_password')

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.application import MIMEApplication


contacts = ['martin@gmail.com']

msg = EmailMessage()
msg['Subject'] = 'Table'
msg['From'] = email
msg['To'] = (", ").join(contacts)

msg.set_content('Table')

text_part = msg.iter_parts()
text_part
msg.add_alternative(html_file, subtype='html')

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(email, password)
    smtp.send_message(msg)